# Generated by Django 3.2.13 on 2022-05-03 15:00

from django.db import migrations, models
import papers.models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0002_uuidtaggeditem_alter_record_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=papers.models.file_path),
        ),
        migrations.DeleteModel(
            name='File',
        ),
    ]
