# Generated by Django 3.2.13 on 2022-05-03 11:45

from django.db import migrations, models
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ("papers", "0002_uuidtaggeditem_alter_record_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="mimetype",
            field=models.CharField(
                choices=[("application/pdf", "Pdf")],
                default="application/pdf",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="file",
            name="path",
            field=models.FilePathField(path=settings.FILESTORAGE_DIR, recursive=True),
        ),
    ]
